version: "3.9"

services:
  mcp-webscraper:
    build: ./srcs/mcp_webscraper
    container_name: webscraper
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Prague
    networks:
      - webscraper-net

  llm:
    build:
      context: ./srcs/LLM
    container_name: crew_ai_test
    ports:
      - "5050:5050"
    depends_on:
      - mcp-webscraper
    networks:
      - webscraper-net

  ollama:
    build:
      context: ./srcs/LLM
    container_name: test_ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
      
volumes:
  ollama_data:

networks:
  webscraper-net:
    driver: bridge
