version: "3.9"

services:
  mcp-webscraper:
    build:
      context: ./srcs/mcp_webscraper
      dockerfile: Dockerfile
    container_name: webscraper
    ports:
      - "8081:8080"
    environment:
      - TZ=Europe/Prague
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=gemma3:1b
    networks:
      - webscraper-net
    depends_on:
      - ollama
    volumes:
      - ./srcs/mcp_webscraper:/usr/src/app
    # Required for Playwright browser dependencies
    cap_add:
      - SYS_ADMIN

  ollama:
    image: ollama/ollama:latest
    container_name: test_ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - webscraper-net

volumes:
  ollama_data:

networks:
  webscraper-net:
    driver: bridge