version: "3.9"

services:
  mcp-webscraper:
    build: ./srcs/mcp_webscraper
    container_name: webscraper
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Prague
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    networks:
      - webscraper-net

  ollama:
    build:
      context: ./srcs/ollama
      dockerfile: Dockerfile # Assuming the Dockerfile is named as such
    container_name: test_ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - webscraper-net

volumes:
  ollama_data:

networks:
  webscraper-net:
    driver: bridge
